use std::collections::HashMap;

pub struct TitleMap {

}

impl TitleMap {

    pub fn create_hashmap() -> HashMap<&'static str, &'static str> {
        let mut map = HashMap::new();

        map.insert("GE", "GEN");
        map.insert("GN", "GEN");
        map.insert("GEN", "GEN");
        map.insert("GENESIS", "GEN");
        map.insert("EX", "EXO");
        map.insert("EXO", "EXO");
        map.insert("EXOD", "EXO");
        map.insert("EXODUS", "EXO");
        map.insert("LV", "LEV");
        map.insert("LEV", "LEV");
        map.insert("LEVITICUS", "LEV");
        map.insert("NU", "NUM");
        map.insert("NM", "NUM");
        map.insert("NUM", "NUM");
        map.insert("NUMBERS", "NUM");
        map.insert("DT", "DEU");
        map.insert("DEU", "DEU");
        map.insert("DEUT", "DEU");
        map.insert("DEUTERONOMY", "DEU");
        map.insert("JOS", "JOS");
        map.insert("JOSH", "JOS");
        map.insert("JOSHUA", "JOS");
        map.insert("JDG", "JDG");
        map.insert("JUDG", "JDG");
        map.insert("JUDGES", "JDG");
        map.insert("RU", "RUT");
        map.insert("RUT", "RUT");
        map.insert("RUTH", "RUT");
        map.insert("1SA", "1SA");
        map.insert("1SM", "1SA");
        map.insert("1SAM", "1SA");
        map.insert("1SAMUEL", "1SA");
        map.insert("ISAM", "1SA");
        map.insert("ISAMUEL", "1SA");
        map.insert("2SA", "2SA");
        map.insert("2SM", "2SA");
        map.insert("2SAM", "2SA");
        map.insert("2SAMUEL", "2SA");
        map.insert("IISA", "2SA");
        map.insert("IISAM", "2SA");
        map.insert("IISAMUEL", "2SA");
        map.insert("1KG", "1KI");
        map.insert("1KI", "1KI");
        map.insert("1KGS", "1KI");
        map.insert("1KINGS", "1KI");
        map.insert("IKI", "1KI");
        map.insert("IKINGS", "1KI");
        map.insert("2KG", "2KI");
        map.insert("2KI", "2KI");
        map.insert("2KGS", "2KI");
        map.insert("2KINGS", "2KI");
        map.insert("IIKI", "2KI");
        map.insert("IIKINGS", "2KI");
        map.insert("1CH", "1CH");
        map.insert("1CHR", "1CH");
        map.insert("1CHRON", "1CH");
        map.insert("1CHRONICLES", "1CH");
        map.insert("ICH", "1CH");
        map.insert("ICHRON", "1CH");
        map.insert("ICHRONICLES", "1CH");
        map.insert("2CH", "2CH");
        map.insert("2CHR", "2CH");
        map.insert("2CHRON", "2CH");
        map.insert("2CHRONICLES", "2CH");
        map.insert("IICH", "2CH");
        map.insert("IICHRON", "2CH");
        map.insert("IICHRONICLES", "2CH");
        map.insert("EZR", "EZR");
        map.insert("EZRA", "EZR");
        map.insert("NE", "NEH");
        map.insert("NEH", "NEH");
        map.insert("NEHEMIAH", "NEH");
        map.insert("EST", "EST");
        map.insert("ESTH", "EST");
        map.insert("ESTHER", "EST");
        map.insert("JB", "JOB");
        map.insert("JOB", "JOB");
        map.insert("PS", "PSA");
        map.insert("PSA", "PSA");
        map.insert("PSALM", "PSA");
        map.insert("PSALMS", "PSA");
        map.insert("PR", "PRO");
        map.insert("PRO", "PRO");
        map.insert("PRV", "PRO");
        map.insert("PROV", "PRO");
        map.insert("PROVERBS", "PRO");
        map.insert("ECC", "ECC");
        map.insert("ECCL", "ECC");
        map.insert("ECCLES", "ECC");
        map.insert("ECCLESIASTES", "ECC");
        map.insert("SS", "SNG");
        map.insert("SNG", "SNG");
        map.insert("SONG", "SNG");
        map.insert("SONGOFSONGS", "SNG");
        map.insert("SONGOFSOLOMON", "SNG");
        map.insert("IS", "ISA");
        map.insert("ISA", "ISA");
        map.insert("ISAIAH", "ISA");
        map.insert("JER", "JER");
        map.insert("JEREMIAH", "JER");
        map.insert("LA", "LAM");
        map.insert("LAM", "LAM");
        map.insert("LAMENTATIONS", "LAM");
        map.insert("EZ", "EZK");
        map.insert("EZE", "EZK");
        map.insert("EZK", "EZK");
        map.insert("EZEK", "EZK");
        map.insert("EZEKIEL", "EZK");
        map.insert("DA", "DAN");
        map.insert("DN", "DAN");
        map.insert("DAN", "DAN");
        map.insert("DANIEL", "DAN");
        map.insert("HOS", "HOS");
        map.insert("HOSEA", "HOS");
        map.insert("JL", "JOL");
        map.insert("JOE", "JOL");
        map.insert("JOEL", "JOL");
        map.insert("AM", "AMO");
        map.insert("AMO", "AMO");
        map.insert("AMOS", "AMO");
        map.insert("OB", "OBA");
        map.insert("OBA", "OBA");
        map.insert("OBAD", "OBA");
        map.insert("OBADIAH", "OBA");
        map.insert("JNH", "JON");
        map.insert("JON", "JON");
        map.insert("JONAH", "JON");
        map.insert("MI", "MIC");
        map.insert("MIC", "MIC");
        map.insert("MICAH", "MIC");
        map.insert("NA", "NAM");
        map.insert("NAH", "NAM");
        map.insert("NAM", "NAM");
        map.insert("NAHUM", "NAM");
        map.insert("HAB", "HAB");
        map.insert("HABAKKUK", "HAB");
        map.insert("ZEP", "ZEP");
        map.insert("ZEPH", "ZEP");
        map.insert("ZEPHANIAH", "ZEP");
        map.insert("HG", "HAG");
        map.insert("HAG", "HAG");
        map.insert("HAGGAI", "HAG");
        map.insert("ZEC", "ZEC");
        map.insert("ZECH", "ZEC");
        map.insert("ZECHARIAH", "ZEC");
        map.insert("MAL", "MAL");
        map.insert("MALACHI", "MAL");
        map.insert("MT", "MAT");
        map.insert("MAT", "MAT");
        map.insert("MATT", "MAT");
        map.insert("MATTHEW", "MAT");
        map.insert("MK", "MRK");
        map.insert("MAR", "MRK");
        map.insert("MARK", "MRK");
        map.insert("LK", "LUK");
        map.insert("LUK", "LUK");
        map.insert("LUKE", "LUK");
        map.insert("JN", "JHN");
        map.insert("JOHN", "JHN");
        map.insert("AC", "ACT");
        map.insert("ACT", "ACT");
        map.insert("ACTS", "ACT");
        map.insert("RO", "ROM");
        map.insert("ROM", "ROM");
        map.insert("ROMANS", "ROM");
        map.insert("1CO", "1CO");
        map.insert("1COR", "1CO");
        map.insert("1CORINTHIANS", "1CO");
        map.insert("ICO", "1CO");
        map.insert("ICOR", "1CO");
        map.insert("ICORINTHIANS", "1CO");
        map.insert("2CO", "2CO");
        map.insert("2COR", "2CO");
        map.insert("2CORINTHIANS", "2CO");
        map.insert("IICO", "2CO");
        map.insert("IICOR", "2CO");
        map.insert("IICORINTHIANS", "2CO");
        map.insert("GAL", "GAL");
        map.insert("GALATIANS", "GAL");
        map.insert("EPH", "EPH");
        map.insert("EPHESIANS", "EPH");
        map.insert("PHP", "PHP");
        map.insert("PHIL", "PHP");
        map.insert("PHILIPPIANS", "PHP");
        map.insert("COL", "COL");
        map.insert("COLOSSIANS", "COL");
        map.insert("1TH", "1TH");
        map.insert("1THES", "1TH");
        map.insert("1THESS", "1TH");
        map.insert("1THESSALONIANS", "1TH");
        map.insert("ITH", "1TH");
        map.insert("ITHES", "1TH");
        map.insert("ITHESSALONIANS", "1TH");
        map.insert("2TH", "2TH");
        map.insert("2THES", "2TH");
        map.insert("2THESS", "2TH");
        map.insert("2THESSALONIANS", "2TH");
        map.insert("IITH", "2TH");
        map.insert("IITHES", "2TH");
        map.insert("IITHESSALONIANS", "2TH");
        map.insert("1TI", "1TI");
        map.insert("1TM", "1TI");
        map.insert("1TIM", "1TI");
        map.insert("1TIMOTHY", "1TI");
        map.insert("ITI", "1TI");
        map.insert("ITIM", "1TI");
        map.insert("ITIMOTHY", "1TI");
        map.insert("2TI", "2TI");
        map.insert("2TM", "2TI");
        map.insert("2TIM", "2TI");
        map.insert("2TIMOTHY", "2TI");
        map.insert("IITI", "2TI");
        map.insert("IITIM", "2TI");
        map.insert("IITIMOTHY", "2TI");
        map.insert("TI", "TIT");
        map.insert("TIT", "TIT");
        map.insert("TITUS", "TIT");
        map.insert("PHM", "PHM");
        map.insert("PHLM", "PHM");
        map.insert("PHILEM", "PHM");
        map.insert("PHILEMON", "PHM");
        map.insert("HEB", "HEB");
        map.insert("HEBREWS", "HEB");
        map.insert("JAS", "JAS");
        map.insert("JAMES", "JAS");
        map.insert("1PE", "1PE");
        map.insert("1PT", "1PE");
        map.insert("1PET", "1PE");
        map.insert("1PETER", "1PE");
        map.insert("IPE", "1PE");
        map.insert("IPET", "1PE");
        map.insert("IPETER", "1PE");
        map.insert("2PE", "2PE");
        map.insert("2PT", "2PE");
        map.insert("2PET", "2PE");
        map.insert("2PETER", "2PE");
        map.insert("IIPE", "2PE");
        map.insert("IIPET", "2PE");
        map.insert("IIPETER", "2PE");
        map.insert("1JN", "1JN");
        map.insert("1JOHN", "1JN");
        map.insert("IJN", "1JN");
        map.insert("1JO", "1JN");
        map.insert("IJOHN", "1JN");
        map.insert("2JN", "2JN");
        map.insert("2JO", "2JN");
        map.insert("2JOHN", "2JN");
        map.insert("IIJN", "2JN");
        map.insert("IIJOHN", "2JN");
        map.insert("3JN", "3JN");
        map.insert("3JO", "3JN");
        map.insert("3JOHN", "3JN");
        map.insert("IIIJN", "3JN");
        map.insert("IIIJOHN", "3JN");
        map.insert("JUD", "JUD");
        map.insert("JUDE", "JUD");
        map.insert("RV", "REV");
        map.insert("REV", "REV");
        map.insert("REVELATION", "REV");

        map

    }

    pub fn create_vector() -> Vec<String> {
        let mut vec = Vec::new();
        // Ordered by length, since if one title contains another
        // (e.g. "ISAMUEL" and "ISA"), the longer must be first
        vec.push("IITHESSALONIANS".to_string());
        vec.push("1THESSALONIANS".to_string());
        vec.push("2THESSALONIANS".to_string());
        vec.push("ITHESSALONIANS".to_string());
        vec.push("IICORINTHIANS".to_string());
        vec.push("SONGOFSOLOMON".to_string());
        vec.push("1CORINTHIANS".to_string());
        vec.push("2CORINTHIANS".to_string());
        vec.push("ECCLESIASTES".to_string());
        vec.push("ICORINTHIANS".to_string());
        vec.push("IICHRONICLES".to_string());
        vec.push("LAMENTATIONS".to_string());
        vec.push("1CHRONICLES".to_string());
        vec.push("2CHRONICLES".to_string());
        vec.push("DEUTERONOMY".to_string());
        vec.push("ICHRONICLES".to_string());
        vec.push("PHILIPPIANS".to_string());
        vec.push("SONGOFSONGS".to_string());
        vec.push("COLOSSIANS".to_string());
        vec.push("REVELATION".to_string());
        vec.push("EPHESIANS".to_string());
        vec.push("GALATIANS".to_string());
        vec.push("IITIMOTHY".to_string());
        vec.push("LEVITICUS".to_string());
        vec.push("ZECHARIAH".to_string());
        vec.push("ZEPHANIAH".to_string());
        vec.push("1TIMOTHY".to_string());
        vec.push("2TIMOTHY".to_string());
        vec.push("HABAKKUK".to_string());
        vec.push("IISAMUEL".to_string());
        vec.push("ITIMOTHY".to_string());
        vec.push("JEREMIAH".to_string());
        vec.push("NEHEMIAH".to_string());
        vec.push("PHILEMON".to_string());
        vec.push("PROVERBS".to_string());
        vec.push("1SAMUEL".to_string());
        vec.push("2SAMUEL".to_string());
        vec.push("EZEKIEL".to_string());
        vec.push("GENESIS".to_string());
        vec.push("HEBREWS".to_string());
        vec.push("IICHRON".to_string());
        vec.push("IIIJOHN".to_string());
        vec.push("IIKINGS".to_string());
        vec.push("IIPETER".to_string());
        vec.push("ISAMUEL".to_string());
        vec.push("MALACHI".to_string());
        vec.push("MATTHEW".to_string());
        vec.push("NUMBERS".to_string());
        vec.push("OBADIAH".to_string());
        vec.push("1CHRON".to_string());
        vec.push("1KINGS".to_string());
        vec.push("1PETER".to_string());
        vec.push("1THESS".to_string());
        vec.push("2CHRON".to_string());
        vec.push("2KINGS".to_string());
        vec.push("2PETER".to_string());
        vec.push("2THESS".to_string());
        vec.push("DANIEL".to_string());
        vec.push("ECCLES".to_string());
        vec.push("ESTHER".to_string());
        vec.push("EXODUS".to_string());
        vec.push("HAGGAI".to_string());
        vec.push("ICHRON".to_string());
        vec.push("IIJOHN".to_string());
        vec.push("IITHES".to_string());
        vec.push("IKINGS".to_string());
        vec.push("IPETER".to_string());
        vec.push("ISAIAH".to_string());
        vec.push("JOSHUA".to_string());
        vec.push("JUDGES".to_string());
        vec.push("PHILEM".to_string());
        vec.push("PSALMS".to_string());
        vec.push("ROMANS".to_string());
        vec.push("1JOHN".to_string());
        vec.push("1THES".to_string());
        vec.push("2JOHN".to_string());
        vec.push("2THES".to_string());
        vec.push("3JOHN".to_string());
        vec.push("HOSEA".to_string());
        vec.push("IICOR".to_string());
        vec.push("IIIJN".to_string());
        vec.push("IIPET".to_string());
        vec.push("IISAM".to_string());
        vec.push("IITIM".to_string());
        vec.push("IJOHN".to_string());
        vec.push("ITHES".to_string());
        vec.push("JAMES".to_string());
        vec.push("JONAH".to_string());
        vec.push("MICAH".to_string());
        vec.push("NAHUM".to_string());
        vec.push("PSALM".to_string());
        vec.push("TITUS".to_string());
        vec.push("1CHR".to_string());
        vec.push("1COR".to_string());
        vec.push("1KGS".to_string());
        vec.push("1PET".to_string());
        vec.push("1SAM".to_string());
        vec.push("1TIM".to_string());
        vec.push("2CHR".to_string());
        vec.push("2COR".to_string());
        vec.push("2KGS".to_string());
        vec.push("2PET".to_string());
        vec.push("2SAM".to_string());
        vec.push("2TIM".to_string());
        vec.push("ACTS".to_string());
        vec.push("AMOS".to_string());
        vec.push("DEUT".to_string());
        vec.push("ECCL".to_string());
        vec.push("ESTH".to_string());
        vec.push("EXOD".to_string());
        vec.push("EZEK".to_string());
        vec.push("EZRA".to_string());
        vec.push("ICOR".to_string());
        vec.push("IICH".to_string());
        vec.push("IICO".to_string());
        vec.push("IIJN".to_string());
        vec.push("IIKI".to_string());
        vec.push("IIPE".to_string());
        vec.push("IISA".to_string());
        vec.push("IITH".to_string());
        vec.push("IITI".to_string());
        vec.push("IPET".to_string());
        vec.push("ISAM".to_string());
        vec.push("ITIM".to_string());
        vec.push("JOEL".to_string());
        vec.push("JOHN".to_string());
        vec.push("JOSH".to_string());
        vec.push("JUDE".to_string());
        vec.push("JUDG".to_string());
        vec.push("LUKE".to_string());
        vec.push("MARK".to_string());
        vec.push("MATT".to_string());
        vec.push("OBAD".to_string());
        vec.push("PHIL".to_string());
        vec.push("PHLM".to_string());
        vec.push("PROV".to_string());
        vec.push("RUTH".to_string());
        vec.push("SONG".to_string());
        vec.push("ZECH".to_string());
        vec.push("ZEPH".to_string());
        vec.push("1CH".to_string());
        vec.push("1CO".to_string());
        vec.push("1JN".to_string());
        vec.push("1JO".to_string());
        vec.push("1KG".to_string());
        vec.push("1KI".to_string());
        vec.push("1PE".to_string());
        vec.push("1PT".to_string());
        vec.push("1SA".to_string());
        vec.push("1SM".to_string());
        vec.push("1TH".to_string());
        vec.push("1TI".to_string());
        vec.push("1TM".to_string());
        vec.push("2CH".to_string());
        vec.push("2CO".to_string());
        vec.push("2JN".to_string());
        vec.push("2JO".to_string());
        vec.push("2KG".to_string());
        vec.push("2KI".to_string());
        vec.push("2PE".to_string());
        vec.push("2PT".to_string());
        vec.push("2SA".to_string());
        vec.push("2SM".to_string());
        vec.push("2TH".to_string());
        vec.push("2TI".to_string());
        vec.push("2TM".to_string());
        vec.push("3JN".to_string());
        vec.push("3JO".to_string());
        vec.push("ACT".to_string());
        vec.push("AMO".to_string());
        vec.push("COL".to_string());
        vec.push("DAN".to_string());
        vec.push("DEU".to_string());
        vec.push("ECC".to_string());
        vec.push("EPH".to_string());
        vec.push("EST".to_string());
        vec.push("EXO".to_string());
        vec.push("EZE".to_string());
        vec.push("EZK".to_string());
        vec.push("EZR".to_string());
        vec.push("GAL".to_string());
        vec.push("GEN".to_string());
        vec.push("HAB".to_string());
        vec.push("HAG".to_string());
        vec.push("HEB".to_string());
        vec.push("HOS".to_string());
        vec.push("ICH".to_string());
        vec.push("ICO".to_string());
        vec.push("IJN".to_string());
        vec.push("IKI".to_string());
        vec.push("IPE".to_string());
        vec.push("ISA".to_string());
        vec.push("ITH".to_string());
        vec.push("ITI".to_string());
        vec.push("JAS".to_string());
        vec.push("JDG".to_string());
        vec.push("JER".to_string());
        vec.push("JNH".to_string());
        vec.push("JOB".to_string());
        vec.push("JOE".to_string());
        vec.push("JON".to_string());
        vec.push("JOS".to_string());
        vec.push("JUD".to_string());
        vec.push("LAM".to_string());
        vec.push("LEV".to_string());
        vec.push("LUK".to_string());
        vec.push("MAL".to_string());
        vec.push("MAR".to_string());
        vec.push("MAT".to_string());
        vec.push("MIC".to_string());
        vec.push("NAH".to_string());
        vec.push("NAM".to_string());
        vec.push("NEH".to_string());
        vec.push("NUM".to_string());
        vec.push("OBA".to_string());
        vec.push("PHM".to_string());
        vec.push("PHP".to_string());
        vec.push("PRO".to_string());
        vec.push("PRV".to_string());
        vec.push("PSA".to_string());
        vec.push("REV".to_string());
        vec.push("ROM".to_string());
        vec.push("RUT".to_string());
        vec.push("SNG".to_string());
        vec.push("TIT".to_string());
        vec.push("ZEC".to_string());
        vec.push("ZEP".to_string());
        vec.push("AC".to_string());
        vec.push("AM".to_string());
        vec.push("DA".to_string());
        vec.push("DN".to_string());
        vec.push("DT".to_string());
        vec.push("EX".to_string());
        vec.push("EZ".to_string());
        vec.push("GE".to_string());
        vec.push("GN".to_string());
        vec.push("HG".to_string());
        vec.push("IS".to_string());
        vec.push("JB".to_string());
        vec.push("JL".to_string());
        vec.push("JN".to_string());
        vec.push("LA".to_string());
        vec.push("LK".to_string());
        vec.push("LV".to_string());
        vec.push("MI".to_string());
        vec.push("MK".to_string());
        vec.push("MT".to_string());
        vec.push("NA".to_string());
        vec.push("NE".to_string());
        vec.push("NM".to_string());
        vec.push("NU".to_string());
        vec.push("OB".to_string());
        vec.push("PR".to_string());
        vec.push("PS".to_string());
        vec.push("RO".to_string());
        vec.push("RU".to_string());
        vec.push("RV".to_string());
        vec.push("SS".to_string());
        vec.push("TI".to_string());

        vec
    }
}
